import { EntityType, AutoRefresh, ApplicationScope } from '@dative-gpi/foundation-shared-domain/enums';
import type { DashboardSettings } from '@dative-gpi/foundation-core-domain/models';

export const settingsMock: DashboardSettings = {
  folderId: null,
  imageId: null,
  image: null,
  labelDefault: 'Dashboard',
  locked: false,
  code: 'dashboard',
  colors: [],
  icon: '',
  tags: [],
  translations: [],
  entityPresetCode: null,
  datePresetCode: null,
  variableCode: null,
  datePresets: [
    {
      hiddenCode: 'last-day',
      labelDefault: 'Last day',
      showInOptions: true,
      startDate: 'now - 1d',
      endDate: 'now',
      useAutoRefresh: false,
      autoRefresh: AutoRefresh.None,
      translations: [],
    },
    {
      hiddenCode: 'last-week',
      labelDefault: 'Last week',
      showInOptions: true,
      startDate: 'now - 7d',
      endDate: 'now',
      useAutoRefresh: false,
      autoRefresh: AutoRefresh.None,
      translations: [],
    },
  ],
  entityPresets: [
    {
      hiddenCode: 'devices',
      labelDefault: 'All devices',
      showInOptions: true,
      singleEntity: false,
      entityType: EntityType.Device,
      entitiesFilters: '',
      entitiesIds: [],
      translations: [],
    },
    {
      hiddenCode: 'locations',
      labelDefault: 'All locations',
      showInOptions: true,
      singleEntity: false,
      entityType: EntityType.Location,
      entitiesFilters: '',
      entitiesIds: [],
      translations: [],
    },
  ],
  variables: [],
  scope: ApplicationScope.None,
};
