export const MILLISECONDS_PER_DAY = 1000 * 60 * 60 * 24;
export const MILLISECONDS_PER_WEEK = MILLISECONDS_PER_DAY * 7;
export const MILLISECONDS_PER_MONTH_APPROX = MILLISECONDS_PER_DAY * 30;
export const MILLISECONDS_PER_YEAR_APPROX = MILLISECONDS_PER_DAY * 365;