export enum Scope {
  None = 0,
  Public = 0b1111,
  Application = 0b1000,
  OrganisationType = 0b10000,
  Organisation = 0b0100,
  User = 0b0010,
  UserOrganisation = 0b0001
}

export enum ApplicationScope {
  None             = 0,
  OrganisationType = 1,
  Organisation     = 2
}

export enum EntityType {
  None = 0,
  Model = 1,
  Group = 2,
  Location = 3,
  Device = 5,
  Alert = 6,
  Scenario = 7,
  User = 8,
  DataCategory = 9,
  DataDefinition = 10,
  ServiceAccount = 11,
  Role = 12,
  Dashboard = 13,
  Organisation = 14,
  OrganisationType = 15,
  Language = 16,
  AuthToken = 19,
  Article = 20,
  Manufacturer = 21,
  Family = 22,
  Folder = 23,
  Chart = 24,
  ChartCategory = 25,
  ConnectivityAlert = 26,
  ConnectivityScenario = 27,
  ScenarioDevice = 28,
  AlertState = 29,
  ChartAxis = 30,
  ChartFilter = 31,
  ChartModifier = 32,
  ChartSerie = 33,
  TimeStep = 34,
  ChartValueRange = 35,
  ValueRange = 36,
  ChartVariable = 37,
  DashboardDatePreset = 38,
  CustomProperty = 39,
  DashboardVariable = 40,
  ScenarioParameter = 41,
  Widget = 42,
  DeviceExplorerElement = 43,
  Grouping = 44,
  Subgrouping = 45
}