name: Generate and publish to Nugets

env:
  GENERATOR_PROJECT_PATH: ci/generators/Foundation.Shared.Translations.Generator
  OUTPUT_PROJECT_PATH: ci/generators/output/Foundation.Shared.Translations

on:
  push:
    tags:
      - "*"

#piepline which run ci/generators/Foundation.Shared.Translations.Generator and publish the output to nuget
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checking out repository
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Run generator
        working-directory: ${{ env.GENERATOR_PROJECT_PATH }}
        run: |
          dotnet restore
          dotnet run

      # pack output project
      - name: Create a NuGet Package 🔧
        working-directory: ${{ env.OUTPUT_PROJECT_PATH }}
        run: |
          dotnet build
          export VERSION=${{ github.ref_name }}
          dotnet pack

      # publish to NuGet
      - name: Publish Package to NuGet 🚀
        working-directory: ${{ env.OUTPUT_PROJECT_PATH }}/bin/Release
        run: |
          dotnet nuget push ${{ env.OUTPUT_PROJECT_PATH }}.${{ github.ref_name }}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
