name: Publish Package to NPM

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
  
    steps:
      # Checking out repository
      - uses: actions/checkout@v3
      
      
      # Setting .npmrc file up to publish to npm
      - name: Setting things up 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # User or organization
          scope: '@dative-gpi'
      
      - name: Install and Build 🔧
        run: |
          npm install
          npm run lint

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate imports map
        run: |
          cd src/shared/foundation-shared-loader
          python importsGenerator.py

      - name: Build foundation-shared-loader
        run: |
          npm install -w @dative-gpi/foundation-shared-loader
          npm run build -w @dative-gpi/foundation-shared-loader

      # Publishing with tag name as version
      - name: Publishing to npm 🚀
        run: |
          lerna publish ${{ github.ref_name }} --exact --no-git-tag-version --yes --no-private --force-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}